### ISSUE TITLE
Example case with fracture

### ISSUE THREAD

**Issue by BinWang0213** [ajacquey/golem#21]
Hi,

Thanks for your nice code ! 

I'd like to reproduce the simulations in the paper below:

Cacace, M. and Jacquey, A. B.: Flexible parallel implicit modelling of coupled thermal–hydraulic–mechanical processes in fractured rocks, Solid Earth, 8, 921-941, https://doi.org/10.5194/se-8-921-2017, 2017.

However, I didn't find any example input files that including fracture, wellbore and model.

Is that possible to share the example file that can help us to learn the GOLEM?

Bin Wang  
PhD Student
Craft & Hawkins Department of Petroleum Engineering
Louisiana State University

**Comment by ajacquey** [comment]
Hi Bin,

We put all the input files which were used to produce the results presented in Cacace & Jacquey (2017), Solid Earth in a [separate repository](https://github.com/ajacquey/golem-examples ).

Please have a look there for the example of interest.

Best,
Antoine

**Comment by BinWang0213** [comment]
Thanks a lot for sharing. Will try those cases.

Best,
Bin
