### ISSUE TITLE
Installation Error with current Moose Version

### ISSUE THREAD

**Issue by Florian-Konrad** [ajacquey/golem#22]
I tried to compile Golem with a fresh Moose installation and got the following error:

> In file included from /home/hombre/projects/Golem/build/unity_src/auxkernels_Unity.C:3:
/home/hombre/projects/Golem/src/auxkernels/GolemEqvInelasticStrain.C: In member function 'virtual libMesh::Real GolemEqvInelasticStrain::computeValue()':
/home/hombre/projects/Golem/src/auxkernels/GolemEqvInelasticStrain.C:44:10: error: '_u_old' was not declared in this scope; did you mean '_dt_old'?
   44 |   return _u_old[_qp] + std::sqrt(2.0 / 3.0) * inelastic_strain_increment.L2norm();
      |          ^~~~~~
      |          _dt_old
In file included from /home/hombre/projects/Golem/build/unity_src/auxkernels_Unity.C:7:
/home/hombre/projects/Golem/src/auxkernels/GolemThermalStress.C: In member function 'virtual libMesh::Real GolemThermalStress::computeValue()':
/home/hombre/projects/Golem/src/auxkernels/GolemThermalStress.C:52:10: error: '_u_old' was not declared in this scope; did you mean '_dt_old'?
   52 |   return _u_old[_qp] + dstressT(_i, _i);
      |          ^~~~~~
      |          _dt_old
/home/hombre/projects/moose/framework/build.mk:118: recipe for target '/home/hombre/projects/Golem/build/unity_src/auxkernels_Unity.x86_64-conda-linux-gnu.opt.lo' failed
make: *** [/home/hombre/projects/Golem/build/unity_src/auxkernels_Unity.x86_64-conda-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by ajacquey** [comment]
Hi Florian,

Good to hear from you. 
Are you using the up-to-date golem version?
I will have a look at that this afternoon and let you know asap.

Best

**Comment by Florian-Konrad** [comment]
Hi Antoine :)
yes I did a complete fresh installation on a clean Ubuntu, so I downloaded the current versions today!

**Comment by mcacace** [comment]
Hi, I though I already answered that but .... no.
Anyway, this is the same problem Guido had some days ago. @ajacquey you just need to do the same as per the latest commit on gitlab (declare _u_old in the Aux).

**Comment by ajacquey** [comment]
> Hi, I though I already answered that but .... no.
> Anyway, this is the same problem Guido had some days ago. @ajacquey you just need to do the same as per the latest commit on gitlab (declare _u_old in the Aux).

Alright, I see. Will do that asap.

**Comment by ajacquey** [comment]
Should be fixed now. 
@Florian-Konrad let me know if that works on your side.

Cheers,

**Comment by Florian-Konrad** [comment]
Works :) Thanks a lot!
