### ISSUE TITLE
Failed to build Golem

### ISSUE THREAD

**Issue by rahulprabhakaran** [ajacquey/golem#23]
I am new to Moose Golem and tried to compile it after successfully installing ad testing the Moose framework without any errors. Following the instructions on the README, I get the following while trying to build. I am running it on Ubuntu subsystem (20.04 LTS) within Windows 10. 

(moose) vi65zebe@DESKTOP-9LJ6NCG:~/projects/golem$ make -j 4
Checking if header needs updating: /home/vi65zebe/projects/moose/framework/include/base/MooseRevision.h...
Rebuilding symlinks in /home/vi65zebe/projects/golem/build/header_symlinks
Creating Unity Directory /home/vi65zebe/projects/golem/build/unity_src
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/src/base/GolemApp.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/src/main.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/test/src/base/GolemTestApp.C...
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/auxkernels_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/kernels_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/controls_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/actions_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/bcs_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/utils_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/userobjects_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/functions_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/dirackernels_Unity.C
Creating Unity /home/vi65zebe/projects/golem/build/unity_src/materials_Unity.C
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/auxkernels_Unity.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/kernels_Unity.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/controls_Unity.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/actions_Unity.C...
In file included from /home/vi65zebe/projects/golem/build/unity_src/kernels_Unity.C:7:
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C: In member function 'virtual void GolemKernelM::computeFiniteDeformJacobian()':
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:194:36: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  194 |   const RankFourTensor II_ijkl = I.mixedProductIkJl(I);
      |                                    ^~~~~~~~~~~~~~~~
      |                                    mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:207:9: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  207 |       I.mixedProductIkJl(rot_times_stress) + I.mixedProductJkIl(rot_times_stress);
      |         ^~~~~~~~~~~~~~~~
      |         mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:207:48: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductJkIl'; did you mean 'mixedProductJkI'?
  207 |       I.mixedProductIkJl(rot_times_stress) + I.mixedProductJkIl(rot_times_stress);
      |                                                ^~~~~~~~~~~~~~~~
      |                                                mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:209:35: error: 'MooseADWrapper<RankTwoTensorTempl<double>, false>' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  209 |       (*_rotation_increment)[_qp].mixedProductIkJl((*_rotation_increment)[_qp]);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:210:45: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  210 |   const RankFourTensor drot_dUhatinv = Fhat.mixedProductIkJl(I);
      |                                             ^~~~~~~~~~~~~~~~
      |                                             mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:217:10: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  217 |       -I.mixedProductIkJl(A) - I.mixedProductJkIl(A) + II_ijkl + I.mixedProductJkIl(I);
      |          ^~~~~~~~~~~~~~~~
      |          mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:217:34: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductJkIl'; did you mean 'mixedProductJkI'?
  217 |       -I.mixedProductIkJl(A) - I.mixedProductJkIl(A) + II_ijkl + I.mixedProductJkIl(I);
      |                                  ^~~~~~~~~~~~~~~~
      |                                  mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:217:68: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductJkIl'; did you mean 'mixedProductJkI'?
  217 |       -I.mixedProductIkJl(A) - I.mixedProductJkIl(A) + II_ijkl + I.mixedProductJkIl(I);
      |                                                                    ^~~~~~~~~~~~~~~~
      |                                                                    mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:223:38: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  223 |       0.5 * II_ijkl - 1.0 / 8.0 * (I.mixedProductIkJl(Ctilde) + Ctilde.mixedProductIkJl(I));
      |                                      ^~~~~~~~~~~~~~~~
      |                                      mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:223:72: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  223 |       0.5 * II_ijkl - 1.0 / 8.0 * (I.mixedProductIkJl(Ctilde) + Ctilde.mixedProductIkJl(I));
      |                                                                        ^~~~~~~~~~~~~~~~
      |                                                                        mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:226:25: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  226 |   drot_dFhatinv -= Fhat.mixedProductIkJl((*_rotation_increment)[_qp].transpose());
      |                         ^~~~~~~~~~~~~~~~
      |                         mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:230:34: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  230 |       -0.5 * II_ijkl + 0.25 * (I.mixedProductIkJl(Ctilde) + Ctilde.mixedProductIkJl(I));
      |                                  ^~~~~~~~~~~~~~~~
      |                                  mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:230:68: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  230 |       -0.5 * II_ijkl + 0.25 * (I.mixedProductIkJl(Ctilde) + Ctilde.mixedProductIkJl(I));
      |                                                                    ^~~~~~~~~~~~~~~~
      |                                                                    mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:233:40: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductJkIl'; did you mean 'mixedProductJkI'?
  233 |   _finite_deform_jacobian[_qp] += Fhat.mixedProductJkIl(_stress[_qp]);
      |                                        ^~~~~~~~~~~~~~~~
      |                                        mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:235:47: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  235 |   const RankFourTensor dFhat_dFhatinv = -Fhat.mixedProductIkJl(Fhat.transpose());
      |                                               ^~~~~~~~~~~~~~~~
      |                                               mixedProductJkI
/home/vi65zebe/projects/golem/src/kernels/GolemKernelM.C:243:51: error: 'const RankTwoTensor' {aka 'const class RankTwoTensorTempl<double>'} has no member named 'mixedProductIkJl'; did you mean 'mixedProductJkI'?
  243 |   const RankFourTensor dFhatinv_dGradu = -Fhatinv.mixedProductIkJl(Finv.transpose());
      |                                                   ^~~~~~~~~~~~~~~~
      |                                                   mixedProductJkI
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/bcs_Unity.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/utils_Unity.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/userobjects_Unity.C...
Compiling C++ (in opt mode) /home/vi65zebe/projects/golem/build/unity_src/functions_Unity.C...
make: *** [/home/vi65zebe/projects/moose/framework/build.mk:144: /home/vi65zebe/projects/golem/build/unity_src/kernels_Unity.x86_64-conda-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....

-------------------------------------------------------------------------------------------------------------------------

**Comment by mcacace** [comment]
@rahulprabhakaran I see. It does seem that there is some deprecated tensor operations (mixedProductIkJL --> mixedProductJkL). @ajacquey could you take care of them?

**Comment by ajacquey** [comment]
> @rahulprabhakaran I see. It does seem that there is some deprecated tensor operations (mixedProductIkJL --> mixedProductJkL). @ajacquey could you take care of them? 

Yes, I'll have a look.

**Comment by mcacace** [comment]
@ajacquey Already up uhm? BTW, thanks!

**Comment by ajacquey** [comment]
So the depreciation of the function `mixedProductIkJl` from the `RankTwoTensor` is now fixed.
However, by updating my `moose` installation to the current one, I encountered a LOT of problems with the current `golem` code (mostly because we use the old `validParams` function)

Working on that now ...

**Comment by mcacace** [comment]
I see. God, it is really old formats! Sorry to keep you busy...

**Comment by ajacquey** [comment]
Should be fine now.
Can you try again @rahulprabhakaran please?

**Comment by ajacquey** [comment]
Closing this issue. Please re-open if problem persists.

**Comment by mfg7** [comment]
Hi. I have the same problem as this person. I could not build, I have the new version of moose
~/projects/Golem$ make -j4
Checking if header needs updating: /home/mariafgg/projects/moose/framework/include/base/MooseRevision.h...
Rebuilding symlinks in /home/mariafgg/projects/Golem/build/header_symlinks
Creating Unity Directory /home/mariafgg/projects/Golem/build/unity_src
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/src/base/GolemApp.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/src/main.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/test/src/base/GolemTestApp.C...
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/auxkernels_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/kernels_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/controls_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/actions_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/bcs_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/utils_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/userobjects_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/functions_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/dirackernels_Unity.C
Creating Unity /home/mariafgg/projects/Golem/build/unity_src/materials_Unity.C
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/auxkernels_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/kernels_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/controls_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/actions_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/bcs_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/utils_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/userobjects_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/functions_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/dirackernels_Unity.C...
Compiling C++ (in opt mode) /home/mariafgg/projects/Golem/build/unity_src/materials_Unity.C...
Linking Library /home/mariafgg/projects/Golem/test/lib/libgolem_test-opt.la...
Linking Library /home/mariafgg/projects/Golem/lib/libgolem-opt.la...
Linking Executable /home/mariafgg/projects/Golem/golem-opt...
/home/mariafgg/mambaforge3/envs/moose/bin/../lib/gcc/x86_64-conda-linux-gnu/10.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/mariafgg/projects/Golem/test/lib/libgolem_test-opt.so: undefined reference to `InputParameters validParams<GolemApp>()'
collect2: error: ld returned 1 exit status
make: *** [/home/mariafgg/projects/moose/framework/app.mk:416: /home/mariafgg/projects/Golem/golem-opt] Error 1

**Comment by ajacquey** [comment]
Hi,

I don't think your issue is related to the previous one.
Are you compiling the most up-to-date `golem` version? 
Is your `MOOSE` installation working? (passing all tests and so on)

I don't manage to reproduce your error so far.
EDIT: I have the same error now, let me look into this.

**Comment by ajacquey** [comment]
I just updated the `master` branch now fixing this bug.

@mfg7  could you try again and confirm me that it also works for you please?

**Comment by mfg7** [comment]
@ajacquey Thank you. It worked :)
