### ISSUE TITLE
Investigate test failure with new MOOSE

### ISSUE THREAD

**Issue by lindsayad** [ajacquey/golem#25]
As outlined in idaholab/moose#24499 the `THM_doublet` test is failing with new MOOSE.

**Comment by lindsayad** [comment]
@ajacquey I was planning to do this, but will hold off if you're investigating!

**Comment by ajacquey** [comment]
After updating MOOSE, I got some compiling errors in `GolemKernelTimeT.C` related to old synthax in `computeResidual` and `computeJacobian`

**Comment by lindsayad** [comment]
As stated in idaholab/moose#24499 I believe this may be due to https://github.com/idaholab/moose/pull/24018

**Comment by ajacquey** [comment]
Yes, I think I have found a fix.
I'm running the input file in question `doublet_THM.i` now to test if the issue remains

**Comment by lindsayad** [comment]
Yea I can fix that as well. Why don't you go ahead and assign me to this?

**Comment by lindsayad** [comment]
Ah ok. You were able to update the `residualBlock` and `jacobianBlock` failures?

**Comment by ajacquey** [comment]
I think so. I will open a PR so you can have a look to be sure.
Thanks
